language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
sudo: required
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 PACKAGE="asl"
  - OCAML_VERSION=4.02 PACKAGE="asl"
